from AttentiveFP_codes.AttentiveLayers import Fingerprint
from AttentiveFP_codes.AttentiveLayers_viz import Fingerprint_viz
from AttentiveFP_codes.getFeatures import save_smiles_dicts, get_smiles_dicts, get_smiles_array, moltosvg_highlight